version: '3'

volumes:
  final_form_local_postgres_data: {}
  final_form_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Docker/local/django/Dockerfile
    image: Discourse_local_django
    container_name: Discourse_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./Docker/production/postgres/Dockerfile
    image: Discourse_production_postgres
    container_name: Discourse_local_postgres
    volumes:
      - Discourse_local_postgres_data:/var/lib/postgresql/data:Z
      - Discourse_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres


